name: dadguide2
description: DadGuide v2 - Helper for Puzzle and Dragons

# Overridden at build time.
version: 2.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase plugins
  firebase_core: ^0.4.3
  firebase_admob: ^0.9.0+10
  firebase_analytics: ^5.0.9
  firebase_auth: ^0.16.0
  firebase_crashlytics: ^0.1.2+3
  firebase_performance: ^0.3.1+5
  firebase_remote_config: ^0.3.0+1
  # cloud_firestore: ^0.13.5
  google_sign_in: ^4.4.2


  sqflite: ^1.3.0
  path_provider: ^1.6.5

  stack_trace: ^1.9.3
  cached_network_image: ^2.0.0
  # If updating this, need to verify cache.dart
  flutter_cache_manager: 1.1.3
  protobuf: any

  # Database codegen
  # TODO: look into upgrading to 2.0
  moor_flutter: ^1.7.0

  # Notifications
  background_fetch: 0.5.4
  flutter_local_notifications: ^1.3.0
  flash: ^1.2.0

  # Injection
  provider: ^4.0.4

  # Settings page
  # TODO: review new 5.0 features for use in settings dialog
  preferences: ^5.1.0

  # Date/internationalization stuff
  intl: ^0.16.0

  # Http downloads
  dio: ^3.0.9

  # Logging
  flutter_fimber: ^0.4.0
  fimber_io: ^0.4.0

  # More icons
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.0.0

  # Dependency injection
  get_it: ^4.0.1

  # Utilities
  quiver: '>=2.0.0 <3.0.0'
  tuple: ^1.0.3

  # Date picker
  flutter_datetime_picker: ^1.3.5

  # Send bad data email
  flutter_email_sender: ^2.2.2
  get_version: ^0.2.1
  device_info: ^0.4.2+1

  # Open YouTube app
  url_launcher: ^5.4.2

  # String formatting
  strings: ^0.1.2

  # Better stream patterns
  rxdart: ^0.23.1

  # Play animations
  video_player: ^0.10.8+1

  # Translate from hiragana to katakana and back
  kana: ^1.0.0

  # Assets for login buttons
  flutter_auth_buttons: ^0.8.0

  # Serialize data
  json_annotation: ^3.0.1

  # IAP for removing ads
  in_app_purchase: ^0.3.3

  # Track widget visibility
  visibility_detector: ^0.1.4

  # Take screenshots of widgets
  screenshot: ^0.1.1

  # Save screenshots in the gallery
  gallery_saver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Database codegen
  moor_generator: ^1.7.0
  build_runner:

  flutter_launcher_icons: ^0.7.4

  # i10n utilities
  intl_translation: ^0.17.7

  # Serialize data
  json_serializable: ^3.2.3

# To rebuild icons, use: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_no_alpha.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_no_alpha.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
